import '@/app/scss/style.scss';
import '@fortawesome/fontawesome-free/css/all.min.css';
import Topbar from '@/app/components/layout/Topbar';
import Footer from '@/app/components/layout/Footer';
import Navbar from '@/app/components/layout/Navbar';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Topbar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
